//Collect Page Tasks
export const ADD_COLLECTION_ITEM = 'ADD_COLLECTION_ITEM'
export const REMOVE_COLLECTION_ITEM = 'REMOVE_COLLECTION_ITEM'


//Process
//Act Or Not
export const MOVE_TO_ACTIONABLE = 'MOVE_TO_ACTIONABLE'
export const MOVE_TO_NONACTIONABLE = 'MOVE_TO_NONACTIONABLE'
//Actionable
export const CHANGE_ACTIONABLE_ITEM = 'CHANGE_ACTIONABLE_ITEM'
export const CHANGE_ACTIONABLE_CONTENT = 'CHANGE_ACTIONABLE_CONTENT'
export const MOVE_ACTION_TO_DO = 'MOVE_ACTION_TO_DO'
export const MOVE_ACTION_TO_DEFER = 'MOVE_ACTION_TO_DEFER'
export const MOVE_ACTION_TO_DELEGATE = 'MOVE_ACTION_TO_DELEGATE'
//Nonactionable
export const NONACTIONABLE_ELIMINATE = 'NONACTIONABLE_ELIMINATE'
    // export const NONACTIONABLE_INCUBATE = 'NONACTIONABLE_INCUBATE'
    // export const NONACTIONABLE_STORE = 'NONACTIONABLE_STORE'
    
//Organize
//Do it?
export const MOVE_FROM_ORGANIZE_TO_DO_IT_NOW = 'MOVE_FROM_ORGANIZE_TO_DO_IT_NOW'
export const MOVE_FROM_ORGANIZE_TO_DO_IT_LATER ='MOVE_FROM_ORGANIZE_TO_DO_IT_LATER'
//Delegate it?

//Defer it?

//Do
export const REMOVE_DO_ACTION = 'REMOVE_DO_ACTION'
export const REMOVE_DO_ITEM = 'REMOVE_DO_ITEM'
   