//Collect Page Tasks
export const ADD_COLLECTION_ITEM = 'ADD_COLLECTION_ITEM'
export const REMOVE_COLLECTION_ITEM = 'REMOVE_COLLECTION_ITEM'
export const MOVE_TO_ACTIONABLE = 'MOVE_TO_ACTIONABLE'
export const MOVE_TO_NONACTIONABLE = 'MOVE_TO_NONACTIONABLE'